### ISSUE TITLE
issues Lizard functions 

### ISSUE THREAD

**Issue by anouksprong** [ArtesiaWater/hydropandas#188]
I discovered some issues while testing the new Lizard functions:

- GroundwaterObs_from_lizard.meta only returns start_hand, start_diver, timeseries_types as metadata
- When a monitoring wells has a tube nr 11 and 1 GroundwaterObs_from_lizard returns tube_nr 11 also when tube_nr 1 is defined.  
 Example: monitoring well EEWP004 

- Type_timeseries = ‘combine’  returns KeyError: 'name'

- When using multiple codes in a list, the tube numbers are overwritten. Therefore, only the last tube number will be used from the second tube 
Example ['39F-0736', '39F-0737']

- When using an extent with multiple pages, only the data of the last page is defined with the function _prepare_API_input 

- BUWP014 raises a ValueError: invalid literal for int() with base 10: '4-2', because the last three characters are not only numbers

**Comment by OnnoEbbens** [comment]
Thanks Anouk, I will have a look so we can discuss them on Friday

**Comment by OnnoEbbens** [comment]
I created a Pull Request to fix these issues. 

- GroundwaterObs_from_lizard.meta only returns start_hand, start_diver, timeseries_types as metadata
The other metadata is saved as attributes in the GroundwaterObs. For 'x' you can use GroundwaterObs.x

- When a monitoring wells has a tube nr 11 and 1 GroundwaterObs_from_lizard returns tube_nr 11 also when tube_nr 1 is defined.
    Example: monitoring well EEWP004
fixed

- Type_timeseries = ‘combine’ returns KeyError: 'name'
fixed

- When using multiple codes in a list, the tube numbers are overwritten. Therefore, only the last tube number will be used from the second tube
    Example ['39F-0736', '39F-0737']
fixed

- When using an extent with multiple pages, only the data of the last page is defined with the function _prepare_API_input
fixed

- BUWP014 raises a ValueError: invalid literal for int() with base 10: '4-2', because the last three characters are not only numbers
This one was kind of a headache. The code 'BUWP014' has 12 tubes but the metadata list contains 19 instances because some tube numbers have 2 or 3 duplicates. This is probably due to replaced tubes or some other administrative issue. In Hydropandas it is rather annoying to have duplicate tubes, therefore I added some code to combine the data from the different tubes. I give a warning if the metadata of tubes with the same tube number differs.

Also added some logging.

**Comment by OnnoEbbens** [comment]
fixed in dev branch
