### ISSUE TITLE
unexpected behaviour `plots.series_per_group`

### ISSUE THREAD

**Issue by HMEUW** [ArtesiaWater/hydropandas#215]
The `plots.series_per_group` function gives an unexpected behaviour.

https://github.com/ArtesiaWater/hydropandas/blob/2426022ead74875a5f5abf6830c405d07533e78c/hydropandas/extensions/plots.py#L740C20-L740C52

**When only one column provided as `by`** 
When `groupname` is a string, than the filename is spoiled with `-` symbols, e.g. `series_by_monitoring_well_group_P-B-4.png` 
When `groupname` is a float or int, the function fails.

My solution is to exclude this line. 

**When a list is provided as `by`** 
You expect something as the `join` function. Therefore 2 lines up, include: `groupname = '-'.join(str(x) for x in groupname)`

Maybe I missed something in the function logic. Otherwise, I will fix this issue.

**Comment by OnnoEbbens** [comment]
I think it is good to remove the line. I would think that `groupname` is never a collection and always a string, int or float. Maybe it is a good idea to add a test or an example for this function in one of the notebooks.

**Comment by dbrakenhoff** [comment]
groupname can actually be a collection. In the case you're grouping on (x, y) locations it is a tuple of the x and y coordinates of that group. 

The issue is that it if it is not a collection but a string the join call will put hyphens between each letter. A simple fix is to check whether groupname is string, and if it is, skip the join call, I think. I'll submit a quick fix.

**Comment by OnnoEbbens** [comment]
Ah that makes sense, thanks for the fix
