### ISSUE TITLE
Easily make an ObsCollection from an existing DataFrame 

### ISSUE THREAD

**Issue by rubencalje** [ArtesiaWater/hydropandas#23]
I am used to reading a certain file-format with observations and creating a Pandas DataFrame from it, where each row of the DataFrame consists of one location. The columns of the DataFrame consist of the metadata of the locations and the time series information is in one of the columns.

Is it possible to easily make an ObsCollection from this DataFrame?

When I do (where df is the DataFrame I mentioned):
`oc = obs.ObsCollection(df)`

I get no error (I expected to get an error).  I cannot use any of the ObsCollection methods however. When I issue the command `pts = oc.to_pastastore()` for example I get the following error:
`AttributeError: 'ObsCollection' object has no attribute 'obs'`

My guess is that I should make Obs-objects, add them to a list, and then call `ObsCollection.form_list()`. Am I right??

**Comment by dbrakenhoff** [comment]
You're right, creating an ObsCollection from another DataFrame is currently not validated at all. This should probably be improved. This is not something we've thought about much, because we almost always work from files using the `from_*` methods.

You can make any DataFrame an ObsCollection right now, but all derived methods will subsequently fail because the ObsCollection expects a column called `obs` that contains `Obs`-objects. 

The method you propose is the best way to go for now:
- First create a list of Obs objects from the timeseries in each row of your dataframe
- Then call `ObsCollection.from_list()`

To improve the package we should either add some validation to the `ObsCollection.__init__()` or add a `from_dataframe()` method. @OnnoEbbens, any idea which would be better?

**Comment by OnnoEbbens** [comment]
Good idea. I think we can create both methods:
- A `from_dataframe()` method with an `obs` argument (that defaults to an `observation.Obs` object). - An `ObsCollection.__init__()` method that can handle multiple inputs. If the input is a DataFrame the `from_dataframe` method is called. If the input is a list of `Obs`-objects we can call the `from_list` method.

**Comment by OnnoEbbens** [comment]
Added some extra options for constructing an ObsCollection. You can now create an ObsCollection:
- from an obs object -> `oc = hpd.ObsCollection(hpd.Obs())`
- from multiple obs objects -> `oc = hpd.ObsCollection(o1, o2, o3)`
- from a list or tuple of observations -> `oc = hpd.ObsCollection([o1, o2, o3])`
- from a dataframe -> `oc = hpd.ObsCollection(pd.DataFrame())`
