### ISSUE TITLE
Reading xml data Dinoloket

### ISSUE THREAD

**Issue by Florisklooster** [ArtesiaWater/hydropandas#72]
BRO data is now also available via Dinoloket. The BRO data, and also some of the DINO data, is available in xml format. If the data of Dinoloket is requested via a zip, the metadata from the wells is delivered in the map 'Grondwatermonitoringput BRO' and the measurement data in the map 'Grondwaterstandonderzoek BRO'. In the comming years there will be increasingly more BRO data available . 
Can you maybe add the functionality of reading this BRO data to your package?

**Comment by dbrakenhoff** [comment]
Thanks for posting your issue. This is definitely something we want to add. Unfortunately it is not at the top of our priorities at the moment. So we're open to contributions, for example scripts for the reading of the BRO XML-data. That would save us some time, and that could allow us to include this functionality earlier.

Any updates on this issue will be posted here.

**Comment by HMEUW** [comment]
I just started with processing BRO XML-data in Python. I used the existing scripts for BRO data about CPTs (Dutch: sonderingen) in the Geolib-plus package (https://github.com/Deltares/geolib-plus) as example.  

I have a first version ready. It reads the GMW-file (Grondwater Monitoring Well), that is send in the BRO-bronhoudersportaal. I will work on a version to read the GMW-file that everyone can download from broloket.nl. Afterwards I will work on the GLD (Groundwater Level Data) files.

Because I used the geolib-plus as example, I will first check whether I can submit my script to the geolib package. Afterwards I will take care for integration with Hydropandas.

**Comment by OnnoEbbens** [comment]
Nice Hendrik! I also started a few days ago with reading the GMW and GLD xml data. I know I should have mentioned this here, I forgot that sorry. I plan to finish this in the first week of January.

I noticed that there is many options to read xml data in Python. So if you are still keen on finishing your script it would be nice to compare our approaches and pick the best of both.
